site_name: GoLedger CC-Tools
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Tutorials: tutorials.md
    - Assets: assets.md
    - Datatypes: datatypes.md
    - Transactions: transactions.md
    - External Tools: external-tools.md
    - Testing: testing.md
    - Functions: functions.md
theme: readthedocs


